# Generated by Django 6.0 on 2025-12-23 15:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(blank=True, editable=False, help_text='ระบบสร้างอัตโนมัติรูปแบบ YY### เช่น 25001', max_length=5, unique=True, verbose_name='รหัสนักเรียน')),
                ('full_name', models.CharField(max_length=255, verbose_name='ชื่อจริงนามสกุล')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='ชื่อเล่น')),
                ('grade_level', models.CharField(blank=True, max_length=50, verbose_name='ระดับชั้น')),
                ('academic_year', models.CharField(blank=True, max_length=20, verbose_name='ปีการศึกษา')),
                ('school_name', models.CharField(blank=True, max_length=255, verbose_name='โรงเรียน')),
                ('parent_phone', models.CharField(max_length=50, verbose_name='เบอร์ผู้ปกครอง')),
                ('contact_channel', models.CharField(choices=[('facebook', 'Facebook'), ('line', 'Line')], default='line', max_length=20, verbose_name='ช่องทางติดต่อ')),
                ('enroll_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='วันที่สมัคร')),
                ('referral_source', models.CharField(choices=[('referral', 'คนแนะนำ'), ('facebook', 'Facebook'), ('google', 'Google'), ('flyer', 'ใบปลิว'), ('walkin', 'เดินผ่าน')], default='referral', max_length=20, verbose_name='ช่องทางที่รู้จัก')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานอยู่')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อวิชา')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TutoringClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อคลาส')),
                ('course_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาคอร์ส (เต็ม)')),
                ('hours_per_session', models.DecimalField(decimal_places=2, default=3.0, max_digits=4, verbose_name='ชั่วโมงต่อครั้ง')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(choices=[('normal_10', 'ต่อคอร์สปกติ (10 ครั้ง)'), ('normal_20', 'ต่อคอร์สปกติ (20 ครั้ง)'), ('first_trial_11', 'สมัครครั้งแรกแบบทดลองเรียน (11 ครั้ง)'), ('first_bonus_12', 'สมัครครั้งแรกแบบแถม (12 ครั้ง)'), ('special', 'กรณีพิเศษ')], default='normal_10', max_length=30, verbose_name='ประเภทการสมัคร')),
                ('sessions_total', models.IntegerField(default=10, verbose_name='จำนวนครั้งทั้งหมด')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remark', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('closed_reason', models.CharField(blank=True, choices=[('renew', 'ต่อคอร์ส'), ('not_renew', 'ไม่ต่อคอร์ส')], max_length=20, null=True, verbose_name='ผลการจบคอร์ส')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่จบคอร์ส')),
                ('payment_type', models.CharField(choices=[('full', 'ชำระเต็ม'), ('installment', 'แบ่งชำระ')], default='full', max_length=20, verbose_name='รูปแบบการชำระ')),
                ('installments_count', models.PositiveIntegerField(default=1, verbose_name='จำนวนงวด')),
                ('course_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาคอร์ส (จาก Class)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ส่วนลด')),
                ('net_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาสุทธิ')),
                ('notified_near_complete', models.BooleanField(default=False, verbose_name='แจ้งเตือนครบคอร์สแล้ว')),
                ('notified_method', models.CharField(blank=True, choices=[('line', 'แจ้งทาง Line'), ('facebook', 'แจ้งทาง FB'), ('paper', 'แจ้งทางใบ')], max_length=20, null=True, verbose_name='ช่องทางที่แจ้งเตือน')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่แจ้งเตือน')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.student')),
                ('tutoring_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.tutoringclass')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='รหัสชีท')),
                ('title', models.CharField(max_length=255, verbose_name='เรื่อง')),
                ('total_pages', models.PositiveIntegerField(default=0, verbose_name='จำนวนหน้า')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='จำนวนข้อ')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sheets', to='core.subject')),
            ],
            options={
                'verbose_name': 'Sheet',
                'verbose_name_plural': 'Sheets',
                'ordering': ('subject__name', 'code'),
            },
        ),
        migrations.CreateModel(
            name='EnrollmentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.PositiveIntegerField(default=1, verbose_name='งวดที่')),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดงวดนี้')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='จ่ายแล้ว')),
                ('is_paid', models.BooleanField(default=False, verbose_name='ชำระครบแล้ว')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่ชำระ')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='core.enrollment')),
            ],
            options={
                'verbose_name': 'Enrollment Installment',
                'verbose_name_plural': 'Enrollment Installments',
                'ordering': ('enrollment_id', 'installment_no'),
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'installment_no'), name='uniq_installment_no_per_enrollment')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='วันที่เช็คชื่อ')),
                ('status', models.CharField(choices=[('present', 'มาเรียน (หัก 1 ครั้ง)'), ('excused', 'ลาเรียน (ไม่หักครั้ง)'), ('no_show', 'ขาดเรียนโดยไม่แจ้ง (หัก 1 ครั้ง)')], default='present', max_length=20, verbose_name='สถานะ')),
                ('deducted', models.BooleanField(default=True, verbose_name='หักครั้ง')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='core.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='core.student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ('-attendance_date', '-checked_at'),
                'constraints': [models.UniqueConstraint(fields=('student', 'enrollment', 'attendance_date'), name='uniq_attendance_per_student_per_day_per_enrollment')],
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.PositiveIntegerField(default=0, verbose_name='ถึงหน้า')),
                ('current_question', models.PositiveIntegerField(default=0, verbose_name='ถึงข้อ')),
                ('last_teacher', models.CharField(blank=True, max_length=100, verbose_name='คนที่สอนครั้งล่าสุด')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('current_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_classes', to='core.sheet', verbose_name='ชีทที่กำลังสอน')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_subjects', to='core.subject')),
                ('tutoring_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='core.tutoringclass')),
            ],
            options={
                'verbose_name': 'Class Subject',
                'verbose_name_plural': 'Class Subjects',
                'ordering': ('tutoring_class__name', 'subject__name'),
                'constraints': [models.UniqueConstraint(fields=('tutoring_class', 'subject'), name='uniq_subject_per_class')],
            },
        ),
    ]
