# Generated by Django 6.0 on 2025-12-23 16:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(blank=True, help_text='ระบบสร้างอัตโนมัติรูปแบบ YY### เช่น 25001', max_length=5, unique=True, verbose_name='รหัสนักเรียน'),
        ),
        migrations.CreateModel(
            name='SheetUpdateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='วันที่')),
                ('page_taught_to', models.PositiveIntegerField(default=0, verbose_name='เลขหน้าที่สอนถึง')),
                ('question_taught_to', models.PositiveIntegerField(default=0, verbose_name='เลขข้อที่สอนถึง')),
                ('last_teacher', models.CharField(blank=True, max_length=100, verbose_name='คนที่สอนครั้งล่าสุด')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_updates', to='core.sheet')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sheet_updates', to='core.subject')),
                ('tutoring_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_updates', to='core.tutoringclass')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sheet Update Entry',
                'verbose_name_plural': 'Sheet Update Entries',
                'ordering': ('-date', 'tutoring_class__name', 'subject__name'),
                'constraints': [models.UniqueConstraint(fields=('tutoring_class', 'subject', 'date'), name='uniq_sheet_update_per_day')],
            },
        ),
    ]
