# Generated by Django 6.0 on 2025-12-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_student_code_sheetupdateentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='sale_run_no',
            field=models.CharField(blank=True, default=None, help_text='ระบบสร้างอัตโนมัติ: {รหัสนักเรียน}-{ลำดับ} เช่น 25001-01', max_length=20, null=True, unique=True, verbose_name='เลขที่รายการขายคอร์ส'),
        ),
    ]
