# Generated by Django 6.0 on 2025-12-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringclass',
            name='total_seats',
            field=models.PositiveIntegerField(default=0, help_text='จำนวนที่นั่งทั้งหมดของห้องนี้ (ใช้คำนวณ ระหว่างเรียน/ที่นั่งว่าง บน Dashboard)', verbose_name='ที่นั่งรวม'),
        ),
    ]
