# Generated by Django 6.0 on 2025-12-25 09:30

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tutoringclass_total_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='จำนวนคงเหลือ')),
                ('is_finished', models.BooleanField(default=False, verbose_name='จบชีทแล้ว')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่จบชีท')),
                ('updated_at', models.DateTimeField(default=timezone.now)),
                ('sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.sheet')),
            ],
            options={
                'verbose_name': 'Sheet Inventory',
                'verbose_name_plural': 'Sheet Inventories',
                'ordering': ('sheet__code',),
            },
        ),
    ]
