"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path
import os

# -------------------------------------------------------------------
# BASE
# -------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# -------------------------------------------------------------------
# SECURITY
# -------------------------------------------------------------------
# อ่านค่าจาก Environment Variable เป็นหลัก
# (ตอนรันในเครื่องยังใช้ค่า default ได้)
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-dev-only-change-this-in-production"
)

DEBUG = os.getenv("DEBUG", "1") == "1"

ALLOWED_HOSTS = (
    os.getenv("ALLOWED_HOSTS", "")
    .split(",")
    if os.getenv("ALLOWED_HOSTS")
    else ["127.0.0.1", "localhost"]
)

CSRF_TRUSTED_ORIGINS = (
    os.getenv("CSRF_TRUSTED_ORIGINS", "")
    .split(",")
    if os.getenv("CSRF_TRUSTED_ORIGINS")
    else []
)


# -------------------------------------------------------------------
# APPLICATIONS
# -------------------------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "core",
]


# -------------------------------------------------------------------
# MIDDLEWARE
# -------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # ✅ สำหรับ production static files
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# -------------------------------------------------------------------
# URL / TEMPLATE
# -------------------------------------------------------------------
ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# -------------------------------------------------------------------
# DATABASE
# -------------------------------------------------------------------
# ค่า default = SQLite (ใช้ในเครื่อง)
# ถ้าขึ้น Cloud (Render / Railway) ให้ตั้ง DATABASE_URL
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# -------------------------------------------------------------------
# PASSWORD VALIDATION
# -------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# -------------------------------------------------------------------
# INTERNATIONALIZATION
# -------------------------------------------------------------------
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True
USE_TZ = True


# -------------------------------------------------------------------
# STATIC FILES (IMPORTANT FOR PRODUCTION)
# -------------------------------------------------------------------
STATIC_URL = "/static/"

# สำหรับ local dev
STATICFILES_DIRS = [
    BASE_DIR / "core" / "static",
]

# สำหรับ production (collectstatic)
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise optimization
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# -------------------------------------------------------------------
# DEFAULT PRIMARY KEY
# -------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "/admin/login/"
LOGIN_REDIRECT_URL = "/dashboard/"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
